ReportDefinitions:
  - reportName: BMCREPORT1
    decryptionPathId: BMCREPORT1
    summary: Report is used for audit and year-end finance reconciliation activities by the ULBs. It also serves as the data dump needed by the ULBs. 
    version: 1.0.0
    moduleName: BMC
    sourceColumns:
      - name: arrivalid
        label: reports.BMC.arrivalid
        type: string
        source: BMC
        total: false
      - name: stakeholderid
        label: reports.BMC.stakeholderid
        type: string
        source: BMC
        total: false
      - name: importpermission
        label: reports.BMC.importpermission
        type: string
        source: BMC
        total: false
      - name: stakeholdername
        label: reports.BMC.stakeholdername
        type: string
        source: BMC
        total: false 
      # - name: user_uuid
      #   label: reports.BMC.user_uuid
      #   type: string
      #   source: BMC
      #   showColumn: false
      # - name: service
      #   label: reports.BMC.servicedetails
      #   type: string
      #   source: BMC
      #   total: false
      #   localisationPrefix: BILLINGSERVICE_BUSINESSSERVICE_
      #   isLocalisationRequired: true
      # - name: amountcollected
      #   label: reports.BMC.amountcollected
      #   type: string
      #   source: BMC
      #   total: true
      # - name: payername
      #   label: reports.BMC.payername
      #   type: string
      #   source: BMC
      #   total: false
      # - name: transactionnumber
      #   label: reports.BMC.transactionnumber
      #   type: string
      #   source: BMC
      #   total: false
      # - name: chequeNo
      #   label: reports.BMC.chequeNo
      #   type: string
      #   source: BMC
      #   total: false
    searchParams:
      # - name: service
      #   label: reports.BMC.service
      #   type: multivaluelist
      #   pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=pb&moduleName=BillingService&masterName=BusinessService&filter=%5B?(@.type=='Adhoc')%5D|$.MdmsRes.BillingService.BusinessService.*.code|$.MdmsRes.BillingService.BusinessService.*.code
      #   source: BMC
      #   wrapper: true
      #   isMandatory: true
      #   searchClause: AND ec.businessService IN ( $service )
      #   isLocalisationRequired: true
      #   localisationPrefix: BILLINGSERVICE_BUSINESSSERVICE_
      # - name: fromDate
      #   label: reports.BMC.fromDate
      #   type: epoch
      #   source: BMC
      #   isMandatory: true
      #   searchClause: AND paydl.receiptdate >= $fromDate
      # - name: toDate
      #   label: reports.BMC.toDate
      #   type: epoch
      #   source: BMC
      #   isMandatory: true
      #   searchClause: AND paydl.receiptdate <= $toDate
      # - name: receiptstatus
      #   label: reports.BMC.receiptstatus
      #   type: singlevaluelist
      #   pattern: 'list://New:New,Deposited:Deposited,Dishonoured:Dishonoured'
      #   source: BMC
      #   isMandatory: false
      #   searchClause: AND pay.paymentstatus <= $receiptstatus
      # - name: collectorname
      #   label: reports.BMC.collectorname
      #   type: singlevaluelist
      #   pattern: http://egov-hrms:8080/egov-hrms/employees/_search?tenantId=$tenantid&roles=UC_EMP|$.Employees[*].user.id|$.Employees[*].user.name|$.Employees[*].user.username
      #   source: BMC
      #   wrapper: true
      #   isMandatory: false
      #   searchClause: AND pay.createdby= $collectorname      

    query: |
          SELECT arrivalid,stakeholderid,importpermission,stakeholdername from eg_deonar_vlistforreantemortem
    orderby: order by arrivalid desc
  
  # - reportName: MCollectCollectionReport
  #   decryptionPathId: MCollectCollectionReport
  #   summary: It helps administrators track the collection in the ULB and the employee collection performance. 
  #   version: 1.0.0
  #   moduleName: BMC
  #   sourceColumns:
  #     - name: service
  #       label: reports.BMC.service
  #       type: string
  #       source: BMC
  #       total: false
  #       localisationPrefix: BILLINGSERVICE_BUSINESSSERVICE_
  #       isLocalisationRequired: true
  #     - name: locality
  #       label: reports.BMC.locality
  #       type: string
  #       source: BMC
  #       total: false
  #       localisationPrefix: TENANTS_MOHALLA_
  #       isLocalisationRequired: true
  #     - name: name
  #       label: reports.BMC.collectorname
  #       type: string
  #       source: BMC
  #       total: false
  #     - name: paymentmode
  #       label: reports.BMC.paymentinstrument
  #       type: string
  #       source: BMC
  #       total: false
  #     - name: totaltransaction
  #       label: reports.BMC.totaltransaction
  #       type: string
  #       source: BMC
  #       total: true
  #     - name: amountcollected
  #       label: reports.BMC.amountcollected
  #       type: string
  #       source: BMC
  #       total: true
  #   searchParams:
  #     - name: service
  #       label: reports.BMC.service
  #       type: multivaluelist
  #       pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=pb&moduleName=BillingService&masterName=BusinessService&filter=%5B?(@.type=='Adhoc')%5D|$.MdmsRes.BillingService.BusinessService.*.code|$.MdmsRes.BillingService.BusinessService.*.code
  #       source: BMC
  #       wrapper: true
  #       isMandatory: true
  #       searchClause: AND ec.businessService IN ( $service )
  #       isLocalisationRequired: true
  #       localisationPrefix: BILLINGSERVICE_BUSINESSSERVICE_
  #     - name: fromDate
  #       label: reports.BMC.fromDate
  #       type: epoch
  #       source: BMC
  #       isMandatory: true
  #       searchClause: AND paydl.receiptdate >= $fromDate
  #     - name: toDate
  #       label: reports.BMC.toDate
  #       type: epoch
  #       source: BMC
  #       isMandatory: true
  #       searchClause: AND paydl.receiptdate <= $toDate
  #     - name: name
  #       label: reports.BMC.collectorname
  #       type: singlevaluelist
  #       pattern: http://egov-hrms:8080/egov-hrms/employees/_search?tenantId=$tenantid&roles=UC_EMP|$.Employees[*].user.id|$.Employees[*].user.name|$.Employees[*].user.username
  #       source: BMC
  #       wrapper: true
  #       isMandatory: false
  #       searchClause: AND pay.createdby = $name
  #     - name: locality
  #       label: reports.BMC.locality
  #       type: singlevaluelist
  #       pattern: http://egov-location.egov:8080/egov-location/location/v11/boundarys/_search?hierarchyTypeCode=ADMIN&boundaryType=Locality&tenantId=$tenantid|$.TenantBoundary[0].boundary.*.code|$.TenantBoundary[0].boundary.*.code
  #       source: BMC
  #       wrapper: true
  #       isMandatory: false
  #       localisationPrefix: TENANTS_MOHALLA_
  #       isLocalisationRequired: true
  #       searchClause: AND eca.locality = $locality
  #     - name: paymentType
  #       label: reports.BMC.paymentType
  #       type: singlevaluelist
  #       pattern: 'list://CASH:CASH,ONLINE:ONLINE,CARD:CARD,DD:DD,CHEQUE:CHEQUE'
  #       source: BMC
  #       wrapper: true
  #       isMandatory: false
  #       isLocalisationRequired: true
  #       localisationPrefix: COMMON_MASTERS_PAYMENTMODE_
  #       searchClause: AND pay.paymentmode = $paymentType
  #   query: |
  #         Select ec.businessService as service, eca.locality as locality, (select name from eg_user where id = pay.createdby::Integer ) as name, 
  #         pay.paymentmode as paymentmode, count(DISTINCT ec.challanNo) as totaltransaction, sum(totalamountpaid) as amountcollected from egcl_bill as b 
  #         inner join egcl_billdetial as bd on b.id = bd.billid AND b.tenantid = bd.tenantid 
  #         inner join eg_echallan as ec on b.consumercode = ec.challanNo and b.tenantid =ec.tenantid 
  #         inner join eg_challan_address as eca on ec.id = eca.echallanId 
  #         inner join egcl_paymentdetail paydl on b.id = paydl.billid and b.tenantid = paydl.tenantid 
  #         inner join egcl_payment pay on paydl.paymentid = pay.id and paydl.tenantid =pay.tenantid where 1=1
  #   groupby: group by service,locality, name, paymentmode

  # - reportName: MCollectChallanRegister
  #   summary: Report is used to track and understand the challans generated, outstanding amount, & different status of the challans. 
  #   version: 1.0.0
  #   moduleName: BMC
  #   sourceColumns:
  #     - name: service
  #       label: reports.BMC.service
  #       type: string
  #       source: BMC
  #       total: false
  #       localisationPrefix: BILLINGSERVICE_BUSINESSSERVICE_
  #       isLocalisationRequired: true
  #     - name: locality
  #       label: reports.BMC.locality
  #       type: string
  #       source: BMC
  #       total: false
  #       localisationPrefix: TENANTS_MOHALLA_
  #       isLocalisationRequired: true
  #     - name: totalchallans
  #       label: reports.BMC.totalchallans
  #       type: string
  #       source: BMC
  #       total: true
  #     - name: status
  #       label: reports.BMC.status
  #       type: string
  #       source: BMC
  #       total: false
  #       localisationPrefix: UC_
  #       isLocalisationRequired: true
  #     - name: totalamount
  #       label: reports.BMC.totalamount
  #       type: string
  #       source: BMC
  #       total: true
  #   searchParams:
  #     - name: service
  #       label: reports.BMC.service
  #       type: singlevaluelist
  #       pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=pb&moduleName=BillingService&masterName=BusinessService&filter=%5B?(@.type=='Adhoc')%5D|$.MdmsRes.BillingService.BusinessService.*.code|$.MdmsRes.BillingService.BusinessService.*.code
  #       source: BMC
  #       wrapper: true
  #       isMandatory: false
  #       searchClause: AND ec.businessService = $service
  #       localisationPrefix: BILLINGSERVICE_BUSINESSSERVICE_
  #       isLocalisationRequired: true
  #     - name: fromDate
  #       label: reports.BMC.fromDate
  #       type: epoch
  #       source: BMC
  #       isMandatory: false
  #       searchClause: AND ec.taxPeriodFrom >= $fromDate
  #     - name: toDate
  #       label: reports.BMC.toDate
  #       type: epoch
  #       source: BMC
  #       isMandatory: false
  #       searchClause: AND ec.taxPeriodTo <= $toDate
  #     - name: status
  #       label: reports.BMC.status
  #       type: singlevaluelist
  #       pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=pb&moduleName=mCollect&masterName=applicationStatus&filter=%5B?(@.active)%5D|$.MdmsRes.mCollect.applicationStatus.*.code|$.MdmsRes.mCollect.applicationStatus.*.code
  #       source: BMC
  #       wrapper: true
  #       isMandatory: false
  #       localisationPrefix: UC_
  #       isLocalisationRequired: true
  #       searchClause: AND ec.applicationStatus = $status
  #     - name: locality
  #       label: reports.BMC.locality
  #       type: singlevaluelist
  #       pattern: http://egov-location.egov:8080/egov-location/location/v11/boundarys/_search?hierarchyTypeCode=ADMIN&boundaryType=Locality&tenantId=$tenantid|$.TenantBoundary[0].boundary.*.code|$.TenantBoundary[0].boundary.*.code
  #       source: BMC
  #       wrapper: true
  #       isMandatory: false
  #       localisationPrefix: TENANTS_MOHALLA_
  #       isLocalisationRequired: true
  #       searchClause: AND eca.locality = $locality  
  #   query: |
  #         select ec.businessService as service , eca.locality as locality, ec.applicationStatus as status, count(DISTINCT ec.challanNo) as totalchallans, sum(bd.totalamount) as totalamount from eg_echallan as ec 
  #         join eg_challan_address as eca on ec.id = eca.echallanId 
  #         join egbs_billdetail_v1 as bd on ec.challanNo = bd.consumercode where 1=1
  #   groupby: group by ec.businessService, eca.locality, ec.applicationStatus
